Feature/12 header toggle
Crew-Wiki/frontend pull request #16
Opened 2024-03-31 08:30 UTC by Todari

# 스크롤 반응형 헤더 구현

## 주요 변경 내용
- 스크롤 방향에 따라 헤더 toggle
- 배경색 영역을 app이 아니라 html 영역으로 변경
- 문서의 길이가 짧을 때, min-height 864px 적용

## 참고 사항
- x

## 남은 작업 내용
- x

## 참고용 시연 사진
- 스크롤에 따른 헤더 변경
https://github.com/Crew-Wiki/frontend/assets/85233397/2b34533c-4023-4556-8e07-2e01f46d6bc3
- 문서의 길이가 짧은 경우
![image](https://github.com/Crew-Wiki/frontend/assets/85233397/b6b37db3-3fbb-4a63-b1a5-e81ad3dbcb0b)

2024-03-31 15:04 UTC, skiende74 commented
main 머지로 되어있는거 merge into dev로 고쳐주세용

2024-03-31 15:05 UTC, Todari commented
오호... 메인이었군

2024-04-01 12:26 UTC, jinhokim98 requested changes
헤더 안으로 넣으세요

2024-04-01 12:26 UTC, jinhokim98 commented on client/src/components/Layout/Layout.tsx
> +  const handleScroll = () => {
헤더 안에서 작성해도 되는 기능 아닐까 생각합니다!
헤더가 보여지고 보여지지 않는 기능으로 보여서

2024-04-01 12:38 UTC, merged